### ISSUE TITLE
Fonts: css declaration must be reviewed

### ISSUE THREAD

**Issue by BernardTatin** [BernardTatin/eleventy-netlify-boilerplate#1]
The way the paths are declared is not good. I don't want the `/_include` in:

```css
@font-face {
    font-family: "Header";
    src: url("/_includes/assets/fonts/DarkerGrotesque/webfont/DarkerGrotesque-Black.woff")
        format("woff");
}
```
